import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import AppProvider from "@/app/app-provider";
import { cookies } from "next/headers";
import SlideSession from "@/components/slide-session";
import accountApi from "@/apiRequests/account";
import { AccountResType } from "@/schemaValidations/account.schema";

const roboto = Roboto({ subsets: ["vietnamese"], weight: ["400", "900"] });

export const metadata: Metadata = {
  title: {
    absolute: "Productic",
    template: "%s | Productic",
    default: "Productic",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user: AccountResType["data"] | null = null;
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppProvider user={user}>
            <Header user={user} />
            <SlideSession />
            {children}
          </AppProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
